import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    loading: 'Loading LYNX...',
    copyright: 'All rights reserved.',
    toggleAdmin: 'Toggle Admin Panel',
    loadingTabs: 'Loading tabs...',
    loadingServices: 'Loading services...',
    loadingValues: 'Loading values...',
    loadingMetrics: 'Loading impact metrics...',
    adminPanel: 'Admin Panel',
    adminSubtitle: 'Manage your LYNX content',
    manageTabs: 'Manage Tabs',
    manageDisciplines: 'Manage Disciplines',
    manageValues: 'Manage Values',
    manageMetrics: 'Manage Metrics',
    contactForms: 'Contact Forms',
    hidden: 'Hidden',
    hideTab: 'Hide tab',
    showTab: 'Show tab',
    noSubmissions: 'No submissions yet',
    totalSubmissions: 'total',
    statusNew: 'New',
    statusRead: 'Read',
    statusResponded: 'Responded',
    yourName: 'Your Name',
    emailAddress: 'Email Address',
    businessName: 'Business Name',
    automationNeeds: 'Tell us about your automation needs...',
    beginJourney: 'Begin the Journey',
    sending: 'Sending...',
    messageSent: 'Message Sent!',
    errorTryAgain: 'Error - Try Again',
    experienceLynx: 'Experience LYNX Intelligence',
    coreDisciplines: 'Core Disciplines',
    coreDisciplinesDesc: 'Five pillars of intelligence that drive measurable transformation.',
    ourValues: 'Our Values',
    ourValuesDesc: 'The principles that guide every system we build.',
    engineeredImpact: 'Engineered for Impact',
    engineeredImpactDesc: 'From enterprise operations to creative teams, LYNX has:',
    impactClosing: 'Every number represents real transformation. Every metric reflects measurable clarity and flow in multi-team workflows.',
    activateIntelligence: 'Activate Your LYNX Intelligence',
    activateDesc: 'Clarity, flow, and silent power — ready to transform your business.',
    homeHeadline: 'From Chaos to Clarity.',
    homeSubtitle1: 'We build intelligent systems that work for you — automating complexity, optimizing workflows, and making technology effortless.',
    homeSubtitle2: 'Transform your business with AI-powered solutions that save time, reduce costs, and unlock new possibilities.',
    aboutBadge: 'Intelligence in Motion',
    aboutHeading: 'Intelligence in Motion',
    aboutPara1: 'LYNX exists at the intersection of human creativity and systemic intelligence. For years, we\'ve refined frameworks that make complex operations feel effortless.',
    aboutPara2: 'Every solution is adaptive, every interface alive, every system crafted to anticipate, evolve, and scale.',
    aboutPara3: 'Our work is precise, silent, and invisible — yet its impact is unmistakable. From enterprise operations to individual workflows, LYNX transforms chaos into flow.',
    aboutInfrastructure: 'The Invisible Infrastructure of Clarity',
    aboutPower: 'We power the next generation of creators, companies, and movements.',
    aboutInstinct: 'Instinct meets intelligence, design meets data, emotion meets execution. Every system empowers humans to act decisively and effortlessly.',
    aboutImagine: 'Imagine your business operating as a living organism — every decision informed, every process optimized, every interaction flowing naturally.',
    aboutThat: 'That is LYNX.',
    aboutDecision: 'Every decision informed',
    aboutProcess: 'Every process optimized',
    aboutInteraction: 'Every interaction flowing',
    storyEssence: 'Our Essence',
    storyEyeBuilds: 'We Are the Eye That Builds',
    storyManifesto: 'Brand Manifesto',
    storyBuilders: 'We are builders of the invisible.\nArchitects of systems that think, adapt, and evolve.',
    storyNoise: 'In a world drowning in noise and repetition, we see patterns others miss.\nWe design intelligence — not to replace humanity, but to amplify it.',
    storyBorn: 'LYNX was born from observation — from the belief that clarity creates power.\nEvery workflow, every process, every connection can be sharpened, automated, perfected.',
    storyTrends: 'We don\'t chase trends.\nWe build foundations — systems that last, learn, and expand.\nBecause real innovation isn\'t about doing more; it\'s about doing better — with precision, focus, and awareness.',
    storyForce: 'We are the quiet force behind evolution.\nThe eye that sees beyond.\nThe mind that builds what others only imagine.',
    storyWeAreLynx: 'We are LYNX — The Eye That Builds.',
    storyMission: 'Mission',
    storyMissionText: 'To create intelligent systems that transform time into value, and complexity into clarity.',
    storyVision: 'Vision',
    storyVisionText: 'To become the world\'s most trusted AI automation collective, building seamless digital ecosystems for global brands and entrepreneurs.',
    storyValues: 'Values',
    valueRespect: 'Respect',
    valueRespectDesc: 'Every interaction builds trust.',
    valueResponsibility: 'Responsibility',
    valueResponsibilityDesc: 'We own every outcome.',
    valueEfficiency: 'Efficiency',
    valueEfficiencyDesc: 'We refine until only clarity remains.',
    valueInnovation: 'Innovation',
    valueInnovationDesc: 'We evolve faster than the system.',
    valuePerspicacity: 'Perspicacity',
    valuePerspicacityDesc: 'We see what others overlook.',
  },
  es: {
    loading: 'Cargando LYNX...',
    copyright: 'Todos los derechos reservados.',
    toggleAdmin: 'Alternar Panel de Administración',
    loadingTabs: 'Cargando pestañas...',
    loadingServices: 'Cargando servicios...',
    loadingValues: 'Cargando valores...',
    loadingMetrics: 'Cargando métricas de impacto...',
    adminPanel: 'Panel de Administración',
    adminSubtitle: 'Gestiona tu contenido LYNX',
    manageTabs: 'Gestionar Pestañas',
    manageDisciplines: 'Gestionar Disciplinas',
    manageValues: 'Gestionar Valores',
    manageMetrics: 'Gestionar Métricas',
    contactForms: 'Formularios de Contacto',
    hidden: 'Oculto',
    hideTab: 'Ocultar pestaña',
    showTab: 'Mostrar pestaña',
    noSubmissions: 'Aún no hay envíos',
    totalSubmissions: 'total',
    statusNew: 'Nuevo',
    statusRead: 'Leído',
    statusResponded: 'Respondido',
    yourName: 'Tu Nombre',
    emailAddress: 'Correo Electrónico',
    businessName: 'Nombre del Negocio',
    automationNeeds: 'Cuéntanos sobre tus necesidades de automatización...',
    beginJourney: 'Comienza el Viaje',
    sending: 'Enviando...',
    messageSent: '¡Mensaje Enviado!',
    errorTryAgain: 'Error - Intenta de Nuevo',
    experienceLynx: 'Experimenta la Inteligencia LYNX',
    coreDisciplines: 'Disciplinas Fundamentales',
    coreDisciplinesDesc: 'Cinco pilares de inteligencia que impulsan la transformación medible.',
    ourValues: 'Nuestros Valores',
    ourValuesDesc: 'Los principios que guían cada sistema que construimos.',
    engineeredImpact: 'Diseñado para el Impacto',
    engineeredImpactDesc: 'Desde operaciones empresariales hasta equipos creativos, LYNX ha:',
    impactClosing: 'Cada número representa una transformación real. Cada métrica refleja claridad y flujo medibles en flujos de trabajo multi-equipo.',
    activateIntelligence: 'Activa tu Inteligencia LYNX',
    activateDesc: 'Claridad, flujo y poder silencioso — listo para transformar tu negocio.',
    homeHeadline: 'Del Caos a la Claridad.',
    homeSubtitle1: 'Construimos sistemas inteligentes que trabajan para ti — automatizando la complejidad, optimizando flujos de trabajo y haciendo la tecnología sin esfuerzo.',
    homeSubtitle2: 'Transforma tu negocio con soluciones impulsadas por IA que ahorran tiempo, reducen costos y desbloquean nuevas posibilidades.',
    aboutBadge: 'Inteligencia en Movimiento',
    aboutHeading: 'Inteligencia en Movimiento',
    aboutPara1: 'LYNX existe en la intersección de la creatividad humana y la inteligencia sistémica. Durante años, hemos refinado marcos que hacen que las operaciones complejas se sientan sin esfuerzo.',
    aboutPara2: 'Cada solución es adaptativa, cada interfaz está viva, cada sistema está diseñado para anticipar, evolucionar y escalar.',
    aboutPara3: 'Nuestro trabajo es preciso, silencioso e invisible, pero su impacto es inconfundible. Desde operaciones empresariales hasta flujos de trabajo individuales, LYNX transforma el caos en flujo.',
    aboutInfrastructure: 'La Infraestructura Invisible de la Claridad',
    aboutPower: 'Impulsamos la próxima generación de creadores, empresas y movimientos.',
    aboutInstinct: 'El instinto se encuentra con la inteligencia, el diseño con los datos, la emoción con la ejecución. Cada sistema empodera a los humanos para actuar de manera decisiva y sin esfuerzo.',
    aboutImagine: 'Imagina tu negocio operando como un organismo vivo: cada decisión informada, cada proceso optimizado, cada interacción fluyendo naturalmente.',
    aboutThat: 'Eso es LYNX.',
    aboutDecision: 'Cada decisión informada',
    aboutProcess: 'Cada proceso optimizado',
    aboutInteraction: 'Cada interacción fluyendo',
    storyEssence: 'Nuestra Esencia',
    storyEyeBuilds: 'Somos el Ojo que Construye',
    storyManifesto: 'Manifiesto de Marca',
    storyBuilders: 'Somos constructores de lo invisible.\nArquitectos de sistemas que piensan, se adaptan y evolucionan.',
    storyNoise: 'En un mundo ahogándose en ruido y repetición, vemos patrones que otros no ven.\nDiseñamos inteligencia — no para reemplazar a la humanidad, sino para amplificarla.',
    storyBorn: 'LYNX nació de la observación — de la creencia de que la claridad crea poder.\nCada flujo de trabajo, cada proceso, cada conexión puede ser afilada, automatizada, perfeccionada.',
    storyTrends: 'No perseguimos tendencias.\nConstruimos fundamentos — sistemas que duran, aprenden y se expanden.\nPorque la verdadera innovación no se trata de hacer más; se trata de hacerlo mejor — con precisión, enfoque y conciencia.',
    storyForce: 'Somos la fuerza silenciosa detrás de la evolución.\nEl ojo que ve más allá.\nLa mente que construye lo que otros solo imaginan.',
    storyWeAreLynx: 'Somos LYNX — El Ojo que Construye.',
    storyMission: 'Misión',
    storyMissionText: 'Crear sistemas inteligentes que transformen el tiempo en valor, y la complejidad en claridad.',
    storyVision: 'Visión',
    storyVisionText: 'Convertirnos en el colectivo de automatización de IA más confiable del mundo, construyendo ecosistemas digitales sin problemas para marcas globales y emprendedores.',
    storyValues: 'Valores',
    valueRespect: 'Respeto',
    valueRespectDesc: 'Cada interacción construye confianza.',
    valueResponsibility: 'Responsabilidad',
    valueResponsibilityDesc: 'Somos dueños de cada resultado.',
    valueEfficiency: 'Eficiencia',
    valueEfficiencyDesc: 'Refinamos hasta que solo queda claridad.',
    valueInnovation: 'Innovación',
    valueInnovationDesc: 'Evolucionamos más rápido que el sistema.',
    valuePerspicacity: 'Perspicacia',
    valuePerspicacityDesc: 'Vemos lo que otros pasan por alto.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
